apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/podinfo

transformers:
- labels.yaml

patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
   - op: replace
     path: /metadata/name
     value: podinfo-ks-argocd-matrix
- target:
    kind: Service
    name: .*
  patch: |-
   - op: replace
     path: /metadata/name
     value: podinfo-ks-argocd-matrix
